#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'gpt-server','console_scripts','gpt_server'
__requires__ = 'gpt-server'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('gpt-server', 'console_scripts', 'gpt_server')()
    )
